# Generated by Django 3.0.7 on 2021-02-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_topshot_date_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='topshot',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
