# Generated by Django 3.0.7 on 2021-03-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_topshot_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='topshot',
            name='scrape_date',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
