# Generated by Django 3.0.7 on 2021-03-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_topshot_scrape_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='topshot',
            name='curr_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
