# Generated by Django 3.0.7 on 2021-03-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_topshot_curr_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='topshot',
            name='pic',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
