# Generated by Django 3.0.7 on 2021-03-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_challenge_set_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenege_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='player_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='set_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
