# Generated by Django 3.0.7 on 2021-04-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210309_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='img_link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
