# Generated by Django 3.0.7 on 2021-04-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_topshot_out_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='topshot',
            name='edition',
            field=models.CharField(default='LE', max_length=2),
            preserve_default=False,
        ),
    ]
