# Generated by Django 3.0.7 on 2021-04-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_topshot_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topshot',
            name='price',
        ),
        migrations.AddField(
            model_name='topshot',
            name='close_price',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topshot',
            name='high_price',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topshot',
            name='low_price',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topshot',
            name='open_price',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
